#!/bin/sh
# Downloads jsfxr from npm and writes Sources/BlipsCore/JSFXRSource.swift, which embeds its
# riffwave.js and sfxr.js unchanged, so the app and the blips command run them in JavaScriptCore.
# Usage: ./Scripts/update-jsfxr.sh [version]

set -eu

ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
VERSION=${1:-1.4.1}
OUT="$ROOT/Sources/BlipsCore/JSFXRSource.swift"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

cd "$WORK"
npm pack "jsfxr@$VERSION" --silent >/dev/null
tar xzf "jsfxr-$VERSION.tgz"

if grep -q '"""##' package/riffwave.js package/sfxr.js; then
  echo "jsfxr $VERSION contains the Swift string delimiter. Use a longer one in this script." >&2
  exit 1
fi

{
  echo "// Generated by Scripts/update-jsfxr.sh from jsfxr $VERSION on npm. Don't edit."
  echo "// jsfxr (https://github.com/chr15m/jsfxr) and riffwave.js are in the public domain."
  echo
  echo "enum JSFXRSource {"
  echo "  static let version = \"$VERSION\""
  echo
  echo '  static let riffwave = ##"""'
  awk '1' package/riffwave.js
  echo '"""##'
  echo
  echo '  static let sfxr = ##"""'
  awk '1' package/sfxr.js
  echo '"""##'
  echo "}"
} > "$OUT"

echo "Wrote $OUT from jsfxr $VERSION"
